project:
  type: website

website:
  title: "Analiza CRIX "
  site-url: https://www.analiza-CRIX.com
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

